### ISSUE TITLE
Support for xCode 8.3.3 with Swift 3.1

### ISSUE THREAD

**Issue by benjaminchodroff** [ibm-watson-iot/iota-starter-carsharing#5]
I am receiving compile errors (mainly from CocoaMQTT) when I try to use this application in xCode 8.3.3 with swift 3.1. Do you have any suggestions on how to fix this? I tried updating the Podfile to use the new swift_version and manually updating CocaoMQTT to 1.0.17 -- still facing issues. 

As a workaround, I downloaded xCode 8.2.1 from apple which still supports swift 2.3 legacy support. However, I cannot load the application on my iphone 7 because it is 10.3.2 which no longer supports this older version of application.

**Comment by uchiken** [comment]
done. we support xcode 8.3.3 now.
